#!/bin/bash
set -e
cd $(dirname "$0")
echo "---------- BUILDING ----------"
chmod +x build
chmod +x run
./build
echo "---------- DONE BUILDING ----------"
echo
echo "to run, almamater/run"
echo "optional arguments: almamater/run LIMIT DOMAINNAME"
echo "LIMIT: solutions worse than this LIMIT will not be submitted. default: 440"
echo "DOMAINNAME: domain name to submit as. default: drama.cmu.edu"
echo
