#!/bin/bash
# take "best" from first arg, default to 440
limit=${1:-440}

# take domain name from second arg, default to "cmu.edu"
domain=${2:-cmu.edu}

dir=$(dirname "$0")
${dir}/src/hasher ${limit} | ${dir}/autosubmit "$domain"
